-- MySQL Script generated by MySQL Workbench
-- Mon Sep  5 12:27:11 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ejemplo_producto
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ejemplo_producto` ;

-- -----------------------------------------------------
-- Schema ejemplo_producto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ejemplo_producto` ;
USE `ejemplo_producto` ;

-- -----------------------------------------------------
-- Table `ejemplo_producto`.`CLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ejemplo_producto`.`CLIENTE` ;

CREATE TABLE IF NOT EXISTS `ejemplo_producto`.`CLIENTE` (
  `dni` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NULL,
  `date` VARCHAR(45) NULL,
  `tlfn` VARCHAR(12) NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ejemplo_producto`.`PROVEDORES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ejemplo_producto`.`PROVEDORES` ;

CREATE TABLE IF NOT EXISTS `ejemplo_producto`.`PROVEDORES` (
  `nif` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` TEXT(60) NOT NULL,
  PRIMARY KEY (`nif`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ejemplo_producto`.`Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ejemplo_producto`.`Producto` ;

CREATE TABLE IF NOT EXISTS `ejemplo_producto`.`Producto` (
  `código` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` FLOAT NOT NULL,
  `PROVEDORES_nif` INT NOT NULL,
  PRIMARY KEY (`código`, `PROVEDORES_nif`),
  INDEX `fk_Producto_PROVEDORES1_idx` (`PROVEDORES_nif` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_PROVEDORES1`
    FOREIGN KEY (`PROVEDORES_nif`)
    REFERENCES `ejemplo_producto`.`PROVEDORES` (`nif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ejemplo_producto`.`COMPRA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ejemplo_producto`.`COMPRA` ;

CREATE TABLE IF NOT EXISTS `ejemplo_producto`.`COMPRA` (
  `CLIENTE_dni` INT NOT NULL,
  `Producto_código` INT NOT NULL,
  PRIMARY KEY (`CLIENTE_dni`, `Producto_código`),
  INDEX `fk_CLIENTE_has_Producto_Producto1_idx` (`Producto_código` ASC) VISIBLE,
  INDEX `fk_CLIENTE_has_Producto_CLIENTE_idx` (`CLIENTE_dni` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTE_has_Producto_CLIENTE`
    FOREIGN KEY (`CLIENTE_dni`)
    REFERENCES `ejemplo_producto`.`CLIENTE` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTE_has_Producto_Producto1`
    FOREIGN KEY (`Producto_código`)
    REFERENCES `ejemplo_producto`.`Producto` (`código`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
